// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mrmzoxzxebazmcklbnzo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ybXpveHp4ZWJhem1ja2xibnpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyNzgzMTYsImV4cCI6MjA2MTg1NDMxNn0.uSYLiwfE3nNYNYxyKvb6UP7qzRbiRAb447Fe8-AGSdI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);